# Generated by Django 4.1.7 on 2023-03-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Название')),
                ('tegs', models.CharField(max_length=100, verbose_name='Теги')),
                ('views', models.CharField(max_length=6, verbose_name='Просмотры')),
                ('likes', models.CharField(max_length=6, verbose_name='Понравилось')),
                ('structure', models.CharField(max_length=200, verbose_name='Состав')),
                ('ingredients', models.CharField(max_length=200, verbose_name='Ингредиенты')),
                ('recipe', models.TextField(max_length=1000, verbose_name='Рецепт')),
            ],
        ),
    ]
