# Generated by Django 4.1.7 on 2023-03-08 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_recipe_recipes_alter_recipes_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='tegs',
            new_name='tags',
        ),
    ]
