# Generated by Django 4.1.7 on 2023-03-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_tegs_recipes_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='photo',
            field=models.ImageField(null=True, upload_to='static/main/recipeimage/', verbose_name='Фото'),
        ),
    ]
