# Generated by Django 4.1.7 on 2023-03-10 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_recipes_recipe_alter_recipes_tags_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipes',
            options={'ordering': ['-id'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
