# Generated by Django 4.1.7 on 2023-03-11 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_recipes_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40, verbose_name='Теги')),
            ],
        ),
        migrations.AddField(
            model_name='recipes',
            name='TagsId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.tagsblock'),
        ),
    ]
