# Generated by Django 4.1.7 on 2023-03-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_recipes_tagsid_delete_tagsblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40, verbose_name='Теги')),
                ('slug', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='recipes',
            name='Tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='main.tag'),
        ),
    ]
