# Generated by Django 4.1.7 on 2023-03-11 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_tag_recipes_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-id'], 'verbose_name': 'Теги', 'verbose_name_plural': 'Тег'},
        ),
    ]
