# Generated by Django 4.1.7 on 2023-03-12 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_tag_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='Tags',
            new_name='Tag',
        ),
    ]
