# Generated by Django 4.1.7 on 2023-03-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='Tag',
        ),
        migrations.AddField(
            model_name='recipes',
            name='tag',
            field=models.ManyToManyField(blank=True, to='main.tag'),
        ),
    ]
