# Generated by Django 4.1.7 on 2023-03-17 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_ingredients_structure_remove_recipes_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
    ]
