# Generated by Django 4.1.7 on 2023-03-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_recipes_ingredients_delete_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='views',
        ),
        migrations.AddField(
            model_name='recipes',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='post_views', to='main.ipmodel'),
        ),
    ]
